version: '2'
services:
  ### PHP-FPM CONTAINER ###
  php-fpm:
    build:
        context: ./php-fpm
        dockerfile: Dockerfile-56
    volumes_from:
        - application
    expose:
        - "9000"
    links:
        - workspace

  application:
    build: ./application
    volumes:
        - ../tp/:/var/www/tp

  workspace:
    build:
        context: ./workspace
        args:
            INSTALL_PRESTISSIMO: ${INSTALL_PRESTISSIMO}
    volumes_from:
        - application
    tty: true

  ### Databases Data Container ################################

  data:
      build: ./data
      volumes:
          - /var/lib/mysql:/var/lib/mysql
          - /var/lib/postgres:/var/lib/postgres
          - /var/lib/mariadb:/var/lib/mariadb
          - /var/lib/memcached:/var/lib/memcached
          - /var/lib/redis:/data
          - /var/lib/neo4j:/var/lib/neo4j/data
          - /var/lib/mongo:/data/db

  nginx:
        build: ./nginx
        volumes_from:
            - application
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "8080:80"
            - "4430:443"
        links:
            - php-fpm

  mysql:
        build: ./mysql
        volumes_from:
            - data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: thinkphp
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
